insert into pizza (name,prix, formule , pizzeria) values ("Marguerita", 12.5, "0.25 Kg Tomates + 0.25 kg Huile + 0.5 Kg Mozarella", 1);
insert into pizza (name, prix, formule , pizzeria) values ("Marguerita",12.5, "0.25 Kg Tomates + 0.25 kg Huile + 0.5 Kg Mozarella", 2);
insert into pizza (name, prix, formule , pizzeria) values ("Marguerita",12.5, "0.25 Kg Tomates + 0.25 kg Huile + 0.5 Kg Mozarella", 3);
insert into pizza (name, prix, formule , pizzeria) values ("Marguerita",12.5, "0.25 Kg Tomates + 0.25 kg Huile + 0.5 Kg Mozarella", 4);
insert into pizza (name, prix, formule , pizzeria) values ("Marguerita",12.5, "0.25 Kg Tomates + 0.25 kg Huile + 0.5 Kg Mozarella", 5);
insert into pizza (name, prix, formule , pizzeria) values ("REINE",15.00, "0.25 Kg Tomates + 0.25 kg Huile + 0.25 Kg Mozarella+ 0.25 Kg Champignon", 1);
insert into pizza (name, prix, formule , pizzeria) values ("REINE",15.00, "0.25 Kg Tomates + 0.25 kg Huile + 0.25 Kg Mozarella+ 0.25 Kg Champignon", 2);
insert into pizza (name, prix, formule , pizzeria) values ("REINE",15.00, "0.25 Kg Tomates + 0.25 kg Huile + 0.25 Kg Mozarella+ 0.25 Kg Champignon", 3);
insert into pizza (name, prix, formule , pizzeria) values ("REINE",15.00, "0.25 Kg Tomates + 0.25 kg Huile + 0.25 Kg Mozarella+ 0.25 Kg Champignon", 4);
insert into pizza (name, prix, formule , pizzeria) values ("REINE",15.00, "0.25 Kg Tomates + 0.25 kg Huile + 0.25 Kg Mozarella+ 0.25 Kg Champignon", 5);
insert into pizza (name, prix, formule , pizzeria) values ("NAPOLITAINE",17.00, "0.30 Kg Fromages+ 0.20 Kg Tomates + 0.15 kg Huile + 0.25 Kg Mozarella", 1);	
insert into pizza (name, prix, formule , pizzeria) values ("NAPOLITAINE",17.00, "0.30 Kg Fromages+ 0.20 Kg Tomates + 0.15 kg Huile + 0.25 Kg Mozarella", 2);
insert into pizza (name, prix, formule , pizzeria) values ("NAPOLITAINE",17.00, "0.30 Kg Fromages+ 0.20 Kg Tomates + 0.15 kg Huile + 0.25 Kg Mozarella", 3);	
insert into pizza (name, prix, formule , pizzeria) values ("NAPOLITAINE", 17.00, "0.30 Kg Fromages+ 0.20 Kg Tomates + 0.15 kg Huile + 0.25 Kg Mozarella", 4);	
insert into pizza (name, prix, formule , pizzeria) values ("NAPOLITAINE",17.00, "0.30 Kg Fromages+ 0.20 Kg Tomates + 0.15 kg Huile + 0.25 Kg Mozarella", 5);	
insert into pizza (name, prix, formule , pizzeria) values ("ROMAINE", 16.5," 0.20 Kg Tomates + 0.20 kg Huile + 0.5 Kg Mozarella", 1);
insert into pizza (name, prix, formule , pizzeria) values ("ROMAINE",16.5, " 0.20 Kg Tomates + 0.20 kg Huile + 0.5 Kg Mozarella", 3);
insert into pizza (name, prix, formule , pizzeria) values ("ROMAINE", 16.5, " 0.20 Kg Tomates + 0.20 kg Huile + 0.5 Kg Mozarella", 4);
insert into pizza (name, prix, formule , pizzeria) values ("SICILIENNE",14.5, " 0.30 Kg Tomates + 0.25 kg Huile + 0.35 Kg Mozarella", 3);
insert into pizza (name, prix, formule , pizzeria) values ("SICILIENNE",14.5, " 0.30 Kg Tomates + 0.25 kg Huile + 0.35 Kg Mozarella", 1);
insert into pizza (name, prix, formule , pizzeria) values ("SICILIENNE",14.5, " 0.30 Kg Tomates + 0.25 kg Huile + 0.35 Kg Mozarella", 2);
insert into pizza (name, prix, formule , pizzeria) values ("SICILIENNE",14.5, " 0.30 Kg Tomates + 0.25 kg Huile + 0.35 Kg Mozarella", 5);
insert into pizza (name, prix, formule , pizzeria) values ("CAPRICIOLA",13.5, " 0.30 Kg Tomates + 0.25 kg Huile + 0.35 Kg Mozarella + 0.4 Kg Champignon", 3);
insert into pizza (name, prix, formule , pizzeria) values ("CAPRICIOLA",13.5, " 0.30 Kg Tomates + 0.25 kg Huile + 0.35 Kg Mozarella + 0.4 Kg Champignon", 5);	
insert into pizza (name, prix, formule , pizzeria) values ("CAPRICIOLA",13.5, " 0.40 Kg Tomates + 0.25 kg Huile + 0.35 Kg Mozarella + 0.4 Kg Champignon", 4);
insert into pizza (name, prix, formule , pizzeria) values ("CALZONE",13.00, " 0.30 Kg Tomates + 0.25 kg Huile + 0.2 Kg Mozarella + 0.3 Kg Champignon ", 2);
insert into pizza (name, prix, formule , pizzeria) values ("CALZONE",13.00, " 0.30 Kg Tomates + 0.25 kg Huile + 0.2 Kg Mozarella + 0.3 Kg Champignon ", 3);
insert into pizza (name, prix, formule , pizzeria) values ("HAWAIENNE",12.00, " 0.30 Kg Tomates + 0.25 kg Huile + 0.2 Kg Mozarella + 0.25 Kg Champignon ", 3);
insert into pizza (name, prix, formule , pizzeria) values ("HAWAIENNE",12.00, " 0.30 Kg Tomates + 0.25 kg Huile + 0.2 Kg Mozarella + 0.25 Kg Champignon ", 2);
insert into pizza (name, prix, formule , pizzeria) values ("HAWAIENNE",12.00, " 0.30 Kg Tomates + 0.25 kg Huile + 0.2 Kg Mozarella + 0.25 Kg Champignon ", 1);							